apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: civicpulse
resources:
  - ../../base
images:
  - name: newfolder-backend
    newName: civicpulse/backend
    newTag: latest
  - name: newfolder-frontend
    newName: civicpulse/frontend
    newTag: latest
